#!/bin/sh

# 参数设置 XDG
riverctl spawn 'bash -c "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"'
riverctl spawn 'bash -c "dubs-update-acrivation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"'

# 启动进程
riverctl spawn 'fcitx5 -d'
riverctl spawn 'wbg /home/ht/.config/wallpapers/bg2.png'
riverctl spawn 'waybar'

# 修改键盘
riverctl keyboard-layout -options "ctrl:nocaps" us

# 按键修改
riverctl map normal Super Return spawn 'kitty -e tmux'
riverctl map normal Super+Control Return spawn 'kitty'

riverctl map normal Control Space spawn 'fcitx5-remote -t'
riverctl map normal Super P spawn "wmenu-run -f 'Maple Mono Normal NF CN 14' -S '#9d7cd8' -p ' '   -M '#9d7cd8'"
riverctl map normal Super B spawn "google-chrome-stable"

riverctl map normal Super U focus-output left
riverctl map normal Super I focus-output right
riverctl map normal Super C close
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up

riverctl map normal Super Left send-layout-cmd rivertile "main-ratio +0.1"
riverctl map normal Super Right send-layout-cmd rivertile "main-ratio -0.1"

riverctl map normal Super+Shift Left send-to-output left
riverctl map normal Super+Shift Right send-to-output right

riverctl map normal Super F toggle-fullscreen

# 按键频率修改
riverctl set-repeat 50 200

# Tags
for i in $(seq 1 3); do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags
done

# Cursor
riverctl xcursor-theme Moga-Neon-Blue 48

# layout初始化
riverctl default-layout rivertile
rivertile -outer-padding 2 -main-location right &
